import { defineText } from '@expcat/tigercat-core'

/**
 * 应用级自定义文案（中文），替代 Tigercat 内置 i18n 语言包。
 *
 * 这是单语言应用的推荐方式：使用 `defineText` 直接提供组件文案，
 * 无需引入语言包文件，打包体积更小。文案内容与原 `zh-CN` 语言包保持一致。
 * 如需覆盖单个组件实例的文案，可在该组件上传入 `labels` 属性。
 */
export const appText = defineText({
  common: {
    okText: '确定',
    cancelText: '取消',
    closeText: '关闭',
    loadingText: '加载中...',
    emptyText: '暂无数据',
  },
  select: {
    doneText: '完成',
    placeholder: '请选择',
    emptyText: '暂无选项',
  },
  colorPicker: {
    trigger: '选择颜色',
    panelTitle: '颜色',
    clear: '清空',
    hue: '色相',
    alpha: '透明度',
    value: '颜色值',
    preview: '颜色预览',
    selectPreset: '选择 {color}',
  },
  datePicker: {
    locale: 'zh-CN',
  },
  calendar: {
    previousMonth: '上个月',
    nextMonth: '下个月',
    previousYear: '上一年',
    nextYear: '下一年',
  },
  modal: {
    closeAriaLabel: '关闭',
    okText: '确定',
    cancelText: '取消',
  },
  drawer: {
    closeAriaLabel: '关闭',
  },
  pagination: {
    totalText: '共 {total} 条',
    itemsPerPageText: '条/页',
    jumpToText: '跳至',
    pageText: '页',
    prevPageAriaLabel: '上一页',
    nextPageAriaLabel: '下一页',
    pageAriaLabel: '第 {page} 页',
    pageIndicatorText: '第 {current} 页，共 {total} 页',
  },
  table: {
    emptyText: '暂无数据',
    loadingText: '加载中',
    expandText: '展开',
    collapseText: '收起',
    selectAllText: '全选',
    selectRowAriaLabel: '选择第 {row} 行',
    sortByText: '按 {column} 排序',
    clearSortText: '不排序',
    toolbarAriaLabel: '数据表格工具栏',
    searchPlaceholder: '搜索',
    searchButtonText: '搜索',
    selectedText: '已选择',
    selectedItemsText: '项',
    columnSettingsText: '列设置',
    columnSettingsAriaLabel: '打开列设置',
  },
  formWizard: {
    prevText: '上一步',
    nextText: '下一步',
    finishText: '完成',
  },
  tour: {
    prevText: '上一步',
    nextText: '下一步',
    finishText: '完成',
    closeAriaLabel: '关闭引导',
  },
  taskBoard: {
    emptyColumnText: '暂无任务',
    addCardText: '添加任务',
    wipLimitText: 'WIP 限制: {limit}',
    dragHintText: '拖拽以移动',
    boardAriaLabel: '任务看板',
  },
  inputOtp: {
    groupLabel: '一次性验证码',
    slotLabel: '第 {index} 位，共 {total} 位',
  },
  tagsInput: {
    removeTagLabel: '移除 {tag}',
    clearAllLabel: '清空全部标签',
  },
  upload: {
    selectFileText: '选择文件',
    clickToUploadText: '上传文件',
    buttonAriaLabel: '上传文件',
  },
  dataExport: {
    triggerText: '导出',
    triggerAriaLabel: '导出数据',
    xlsxText: '导出 Excel',
    markdownText: '导出 Markdown',
    exportingText: '导出中...',
  },
  markdownEditor: {
    formattingToolbarAriaLabel: 'Markdown 格式工具栏',
    modeToolbarAriaLabel: 'Markdown 视图模式',
    editorAriaLabel: 'Markdown 编辑器',
    previewAriaLabel: 'Markdown 预览',
    editModeLabel: '编辑',
    splitModeLabel: '分栏',
    previewModeLabel: '预览',
    bold: '加粗',
    italic: '斜体',
    strikethrough: '删除线',
    heading: '标题',
    blockquote: '引用',
    unorderedList: '无序列表',
    orderedList: '有序列表',
    inlineCode: '行内代码',
    codeBlock: '代码块',
    link: '链接',
    image: '图片',
    table: '表格',
    horizontalRule: '分隔线',
  },
  richTextEditor: {
    formattingToolbarAriaLabel: '富文本格式工具栏',
    editorAriaLabel: '富文本编辑器',
    bold: '加粗',
    italic: '斜体',
    underline: '下划线',
    strikethrough: '删除线',
    heading1: '标题1',
    heading2: '标题2',
    heading3: '标题3',
    bulletList: '无序列表',
    orderedList: '有序列表',
    blockquote: '引用',
    codeBlock: '代码',
    link: '链接',
    image: '图片',
    horizontalRule: '分隔线',
    undo: '撤销',
    redo: '重做',
    clear: '清除格式',
  },
})
