using System.Text.Json.Serialization;
using Tigercat.Admin.Api.Auth;
using Tigercat.Admin.Api.Common;
using Tigercat.Admin.Api.Endpoints;
using Tigercat.Admin.Api.EventBus;
// PermissionInfoResponse is now in Tigercat.Admin.Api.Common

namespace Tigercat.Admin.Api.Serialization;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(ApiContracts))]
[JsonSerializable(typeof(RegisterRequest))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(ChangePasswordRequest))]
[JsonSerializable(typeof(TwoFactorVerifyRequest))]
[JsonSerializable(typeof(ForgotPasswordCodeRequest))]
[JsonSerializable(typeof(ForgotPasswordResetRequest))]
[JsonSerializable(typeof(UpdateTwoFactorRequest))]
[JsonSerializable(typeof(ApiResponse<object>))]
[JsonSerializable(typeof(ApiResponse<string>))]
[JsonSerializable(typeof(ApiResponse<UserResponse>))]
[JsonSerializable(typeof(ApiResponse<LoginResponse>))]
[JsonSerializable(typeof(ApiResponse<MessageResponse>))]
[JsonSerializable(typeof(ForgotPasswordCodeResponse))]
[JsonSerializable(typeof(ApiResponse<ForgotPasswordCodeResponse>))]
[JsonSerializable(typeof(TwoFactorStatusResponse))]
[JsonSerializable(typeof(ApiResponse<TwoFactorStatusResponse>))]
[JsonSerializable(typeof(ApiResponse<HealthResponse>))]
[JsonSerializable(typeof(HealthDependencyStatus))]
[JsonSerializable(typeof(Dictionary<string, HealthDependencyStatus>))]
[JsonSerializable(typeof(ApiResponse<InfoResponse>))]
[JsonSerializable(typeof(Dictionary<string, string?>))]
[JsonSerializable(typeof(UserResponse))]
[JsonSerializable(typeof(EventEnvelope))]
[JsonSerializable(typeof(AuditLogItemResponse))]
[JsonSerializable(typeof(AuditLogItemResponse[]))]
[JsonSerializable(typeof(ApiResponse<AuditLogItemResponse>))]
[JsonSerializable(typeof(ApiResponse<AuditLogItemResponse[]>))]
[JsonSerializable(typeof(PagedResponse<AuditLogItemResponse>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<AuditLogItemResponse>>))]
[JsonSerializable(typeof(AuditRetentionPolicyResponse))]
[JsonSerializable(typeof(UpdateAuditRetentionPolicyRequest))]
[JsonSerializable(typeof(ApiResponse<AuditRetentionPolicyResponse>))]
[JsonSerializable(typeof(AuditRetentionCleanupRequest))]
[JsonSerializable(typeof(AuditRetentionCleanupResponse))]
[JsonSerializable(typeof(ApiResponse<AuditRetentionCleanupResponse>))]
// Users CRUD types
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateUserRequest))]
[JsonSerializable(typeof(BatchDeleteUsersRequest))]
[JsonSerializable(typeof(BatchUpdateUserStatusRequest))]
[JsonSerializable(typeof(UserItemResponse))]
[JsonSerializable(typeof(RoleInfoResponse))]
[JsonSerializable(typeof(PagedResponse<UserItemResponse>))]
[JsonSerializable(typeof(ApiResponse<UserItemResponse>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<UserItemResponse>>))]
// Auth permissions
[JsonSerializable(typeof(UserPermissionsResponse))]
[JsonSerializable(typeof(ApiResponse<UserPermissionsResponse>))]
// Roles CRUD types
[JsonSerializable(typeof(CreateRoleRequest))]
[JsonSerializable(typeof(UpdateRoleRequest))]
[JsonSerializable(typeof(SetRolePermissionsRequest))]
[JsonSerializable(typeof(SetRoleUsersRequest))]
[JsonSerializable(typeof(RoleDetailResponse))]
[JsonSerializable(typeof(PermissionInfoResponse))]
[JsonSerializable(typeof(RoleUserInfoResponse))]
[JsonSerializable(typeof(PagedResponse<RoleDetailResponse>))]
[JsonSerializable(typeof(ApiResponse<RoleDetailResponse>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<RoleDetailResponse>>))]
[JsonSerializable(typeof(PermissionInfoResponse[]))]
[JsonSerializable(typeof(ApiResponse<PermissionInfoResponse[]>))]
// Stats types
[JsonSerializable(typeof(StatsOverviewResponse))]
[JsonSerializable(typeof(ApiResponse<StatsOverviewResponse>))]
[JsonSerializable(typeof(TrendPointResponse))]
[JsonSerializable(typeof(StatsTrendResponse))]
[JsonSerializable(typeof(ApiResponse<StatsTrendResponse>))]
// Export types
[JsonSerializable(typeof(ExportUserRow))]
[JsonSerializable(typeof(ExportRoleRow))]
[JsonSerializable(typeof(ExportUserRow[]))]
[JsonSerializable(typeof(ExportRoleRow[]))]
// Settings types
[JsonSerializable(typeof(SettingItemResponse))]
[JsonSerializable(typeof(SettingItemResponse[]))]
[JsonSerializable(typeof(UpdateSettingsRequest))]
[JsonSerializable(typeof(SettingEntry))]
[JsonSerializable(typeof(ApiResponse<SettingItemResponse>))]
[JsonSerializable(typeof(ApiResponse<SettingItemResponse[]>))]
// Media types
[JsonSerializable(typeof(MediaItemResponse))]
[JsonSerializable(typeof(MediaItemResponse[]))]
[JsonSerializable(typeof(MediaDetailResponse))]
[JsonSerializable(typeof(MediaReferenceResponse))]
[JsonSerializable(typeof(MediaReferenceResponse[]))]
[JsonSerializable(typeof(BatchDeleteMediaRequest))]
[JsonSerializable(typeof(DuplicateMediaResponse))]
[JsonSerializable(typeof(MediaOrphanCleanupRequest))]
[JsonSerializable(typeof(MediaOrphanFileResponse))]
[JsonSerializable(typeof(MediaOrphanFileResponse[]))]
[JsonSerializable(typeof(MediaOrphanCleanupResponse))]
[JsonSerializable(typeof(PagedResponse<MediaItemResponse>))]
[JsonSerializable(typeof(ApiResponse<MediaItemResponse>))]
[JsonSerializable(typeof(ApiResponse<DuplicateMediaResponse>))]
[JsonSerializable(typeof(ApiResponse<MediaDetailResponse>))]
[JsonSerializable(typeof(ApiResponse<MediaReferenceResponse[]>))]
[JsonSerializable(typeof(ApiResponse<MediaOrphanCleanupResponse>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<MediaItemResponse>>))]
// Operations workflow types
[JsonSerializable(typeof(NotificationItemResponse))]
[JsonSerializable(typeof(NotificationItemResponse[]))]
[JsonSerializable(typeof(PagedResponse<NotificationItemResponse>))]
[JsonSerializable(typeof(UpdateNotificationReadRequest))]
[JsonSerializable(typeof(MarkNotificationsReadRequest))]
[JsonSerializable(typeof(ApiResponse<NotificationItemResponse>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<NotificationItemResponse>>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(AdminTaskResponse))]
[JsonSerializable(typeof(AdminTaskResponse[]))]
[JsonSerializable(typeof(PagedResponse<AdminTaskResponse>))]
[JsonSerializable(typeof(CreateAdminTaskRequest))]
[JsonSerializable(typeof(UpdateAdminTaskRequest))]
[JsonSerializable(typeof(MoveAdminTaskRequest))]
[JsonSerializable(typeof(CompleteAdminTaskRequest))]
[JsonSerializable(typeof(ApiResponse<AdminTaskResponse>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<AdminTaskResponse>>))]
// Tickets / chat / comments
[JsonSerializable(typeof(TicketMessageResponse))]
[JsonSerializable(typeof(TicketMessageResponse[]))]
[JsonSerializable(typeof(TicketResponse))]
[JsonSerializable(typeof(TicketResponse[]))]
[JsonSerializable(typeof(PagedResponse<TicketResponse>))]
[JsonSerializable(typeof(CreateTicketRequest))]
[JsonSerializable(typeof(UpdateTicketRequest))]
[JsonSerializable(typeof(CreateTicketMessageRequest))]
[JsonSerializable(typeof(ApiResponse<TicketResponse>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<TicketResponse>>))]
[JsonSerializable(typeof(ChatMessageResponse))]
[JsonSerializable(typeof(ChatMessageResponse[]))]
[JsonSerializable(typeof(CreateChatMessageRequest))]
[JsonSerializable(typeof(ApiResponse<ChatMessageResponse>))]
[JsonSerializable(typeof(ApiResponse<ChatMessageResponse[]>))]
[JsonSerializable(typeof(CommentUserResponse))]
[JsonSerializable(typeof(CommentResponse))]
[JsonSerializable(typeof(CommentResponse[]))]
[JsonSerializable(typeof(CreateCommentRequest))]
[JsonSerializable(typeof(ApiResponse<CommentResponse>))]
[JsonSerializable(typeof(ApiResponse<CommentResponse[]>))]
// Projects / calendar
[JsonSerializable(typeof(ProjectMemberResponse))]
[JsonSerializable(typeof(ProjectMemberResponse[]))]
[JsonSerializable(typeof(ProjectActivityResponse))]
[JsonSerializable(typeof(ProjectActivityResponse[]))]
[JsonSerializable(typeof(ProjectResponse))]
[JsonSerializable(typeof(ProjectResponse[]))]
[JsonSerializable(typeof(PagedResponse<ProjectResponse>))]
[JsonSerializable(typeof(ApiResponse<ProjectResponse>))]
[JsonSerializable(typeof(ApiResponse<PagedResponse<ProjectResponse>>))]
[JsonSerializable(typeof(CalendarEventResponse))]
[JsonSerializable(typeof(CalendarEventResponse[]))]
[JsonSerializable(typeof(CreateCalendarEventRequest))]
[JsonSerializable(typeof(ApiResponse<CalendarEventResponse>))]
[JsonSerializable(typeof(ApiResponse<CalendarEventResponse[]>))]
// Content / jobs / import
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(ArticleResponse))]
[JsonSerializable(typeof(ArticleResponse[]))]
[JsonSerializable(typeof(UpdateArticleRequest))]
[JsonSerializable(typeof(ApiResponse<ArticleResponse>))]
[JsonSerializable(typeof(ApiResponse<ArticleResponse[]>))]
[JsonSerializable(typeof(JobResponse))]
[JsonSerializable(typeof(JobResponse[]))]
[JsonSerializable(typeof(CreateJobRequest))]
[JsonSerializable(typeof(UpdateJobRequest))]
[JsonSerializable(typeof(ApiResponse<JobResponse>))]
[JsonSerializable(typeof(ApiResponse<JobResponse[]>))]
[JsonSerializable(typeof(ImportJobResultResponse))]
[JsonSerializable(typeof(ImportJobResponse))]
[JsonSerializable(typeof(CreateImportJobRequest))]
[JsonSerializable(typeof(ApiResponse<ImportJobResponse>))]
internal partial class AppJsonContext : JsonSerializerContext
{
}
