packages:
  - 'Tigercat.Admin.Vue'
  - 'Tigercat.Admin.React'
  - 'Tigercat.Admin.MockApi'
minimumReleaseAgeExclude:
  - '@expcat/tigercat-core@2.4.0 || 2.4.2 || 2.5.0'
  - '@expcat/tigercat-react@2.4.0 || 2.4.2 || 2.5.0'
  - '@expcat/tigercat-vue@2.4.0 || 2.4.2 || 2.5.0'
