packages:
  - 'Tigercat.Admin.Vue'
  - 'Tigercat.Admin.React'
  - 'Tigercat.Admin.MockApi'
minimumReleaseAgeExclude:
  - '@expcat/tigercat-core@2.1.3'
  - '@expcat/tigercat-react@2.1.3'
  - '@expcat/tigercat-vue@2.1.3'
