packages:
  - 'Tigercat.Admin.Vue'
  - 'Tigercat.Admin.React'
  - 'Tigercat.Admin.MockApi'
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@expcat/tigercat-core@2.4.0 || 2.4.2 || 2.5.0 || 2.5.2 || 2.5.4 || 2.6.0 || 2.9.4 || 3.0.0-preview.9 || 3.0.0-rc.1'
  - '@expcat/tigercat-react@2.4.0 || 2.4.2 || 2.5.0 || 2.5.2 || 2.5.4 || 2.6.0 || 2.9.4 || 3.0.0-preview.9 || 3.0.0-rc.1'
  - '@expcat/tigercat-vue@2.4.0 || 2.4.2 || 2.5.0 || 2.5.2 || 2.5.4 || 2.6.0 || 2.9.4 || 3.0.0-preview.9 || 3.0.0-rc.1'
